### ISSUE TITLE
Setup a presentation part

### ISSUE THREAD

**Issue by xivk** [osmbe/road-completion-old#12]
Setup a website where we present the results of the project.

**Comment by xivk** [comment]
@jbelien @joostschouppe I assigned you both here too because Jonathan can create a great website and Joost can handle the data with mapbox... sounds good?

**Comment by jbelien** [comment]
Sounds good to me ! :)

What's the "deadline" ?
I'm quite busy at the moment.

**Comment by joostschouppe** [comment]
November 30th :)

**Comment by xivk** [comment]
Once joost uploadsthe data an initial version could be a full screen map somewhere showing the data... so done in 2 mins I mean. From there we can move on.

**Comment by jbelien** [comment]
Okay, I think I can manage to create something for that day :)

**Comment by xivk** [comment]
Suggestion:

- [x] Setup a gh-pages branch.
- [x] Added domain roads.osm.be to it.
- [x] Use this on the map: https://api.mapbox.com/styles/v1/joostschouppe/cj8bepevu772i2rqwlw00rq4y/tiles/256/%7Bz%7D/%7Bx%7D/%7By%7D?access_token=pk.eyJ1Ijoiam9vc3RzY2hvdXBwZSIsImEiOiJjaWh2djF1c2owMmJrdDNtMWV2c2Rld3QwIn0.9zXJJWZ4rOcspyFIdEC3Rw

**Comment by xivk** [comment]
- [x] Change zoom-levels on the mapbox style, the errors need to be visible on a higher level too.

**Comment by jbelien** [comment]
Will take care of it ASAP!

**Comment by xivk** [comment]
@jbelien I pointed the domain roads.osm.be to this repo so once you add a CNAME file you're good.

**Comment by jbelien** [comment]
http://roads.osm.be/ 👍

**Comment by jbelien** [comment]
Want do you want me to add in the webpage ?
Switch to OSM layer ?
Anything else ?

**Comment by xivk** [comment]
An OSM layer would be nice yes... nothing else for me...:)

**Comment by xivk** [comment]
@jbelien Can you add current view to url?

**Comment by joostschouppe** [comment]
Reference to the source layers, link to the Roadmapping OSM Projects page.
As for extra layers: some of the stuff here light be fun: https://github.com/osmbe/play/blob/master/wegenregister.html

**Comment by xivk** [comment]
haha, requests keep piling up... 👍 sorry @jbelien

**Comment by jbelien** [comment]
> @jbelien Can you add current view to url?

Already working on it !

---

Will add layer switch too !

**Comment by jbelien** [comment]
What do I put as attribution for the Mapbox layer ?

**Comment by joostschouppe** [comment]
© Mapbox © OpenStreetMap, Analysis OpenStreetMap Belgium

**Comment by jbelien** [comment]
- [x] Attribution
- [x] Permalink
- [x] Layer switch
