### ISSUE TITLE
Transparency is a bit too high

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/road-completion-old#23]
In the user interface, with imagery as background, the transparency of the errors is a bit too high to clearly see them in high zoom levels. E.g. https://road-completion.osm.be/#16/50.840738/4.341123

**Comment by jbelien** [comment]
Line to fix : [main.js#L149](https://github.com/osmbe/road-completion-frontend/blob/master/frontend/js/main.js#L149)

**Comment by jbelien** [comment]
Issue moved to https://github.com/osmbe/road-completion-frontend/issues/2
