### ISSUE TITLE
Pass the centroid of the problem to the editor

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/road-completion-old#24]
I don't really know how the parameter for the editor is defined, but seems to be based on the mapbounds of the missing road. That means if the issue is not zoomed in a lot or you haven't centered your map properly, you will be very confused when you arrive in the editor software.

**Comment by jbelien** [comment]
Line to fix : [main.js#L321](https://github.com/osmbe/road-completion-frontend/blob/master/frontend/js/main.js#L321)

**Comment by jbelien** [comment]
Issue moved to https://github.com/osmbe/road-completion-frontend/issues/3
