### ISSUE TITLE
logical code problem in filter

### ISSUE THREAD

**Issue by gplv2** [osmbe/road-completion-old#4]
Given this code:

`// filter out roads that are shorter than 30m and have no name
  tigerRoads.features.forEach(function(road, i) {
    if (filter(road)) tigerRoads.features.splice(i,1);
  });`

It will not do as expected.  Since you modify the array while looping it, the counters will change, you will end up deleting either not enough, or the wrong indexes.

for example : say the filter function has to delete i = 6, 7 and 12 in an object, it will first delete 6 and then the indexes of the same object will shuffle down ,leaving no gap.  But the initial loop isn't over yet.

I'm using some of the code ideas here in GRB tool, hence why I looked into this.

See https://stackoverflow.com/questions/13244888/delete-record-from-javascript-array-object

**Comment by xivk** [comment]
Glenn you are way ahead of us, we have yet to start any actual work on this project... ;-)

**Comment by gplv2** [comment]
I know, isn't it great knowing you'll save hours of future debugging work!! You're welcome ;-)

**Comment by xivk** [comment]
I didn't even manage to get things up and running on my machine... ;-)

**Comment by gplv2** [comment]
I was looking for inspiration on algorithms to compare datasets, I found it .., I'm using bits and pieces from the code here, I'm almost done in fact ;-)   It would not be nice of me to let you guys run into the same issues.   I can't get it to work either but that doesn't mean this is useless :+1:

**Comment by xivk** [comment]
Fixed because it all changed! 👍
