### ISSUE TITLE
Buffer difference

### ISSUE THREAD

**Issue by jbelien** [osmbe/road-completion-old#8]
When we compare road data from OSM data, we use a buffer and then check what's (not) in this buffer.

By using `turf.difference` function we only have the missing (or extra) geometry but not the whole geometry and the data associated to it.

It would be better to have the full geometry and full object of what's missing.

**Comment by joostschouppe** [comment]
I also built in a filter:
"if length outside buffer <10m OR length outside buffer <10% drop from errorlist"
That way you eliminate most mini missings and many false positive dead end streets without removing too many real errors.

**Comment by gplv2** [comment]
Maybe you already know but there is an interesting turf function for this:

`turf.buffer( f.geometry, buffer_meters, 'meters' );`

I actually wrote a WR difference function a long time ago that works pretty well but the only problem there is that it doesn't work too well at junctions.

Other functions that I have in this code (looking at it as I actually added this to my GRB thing to play with turf):

`turf.intersect` & `turf.difference`

I'm pretty sure you know about those two already.   I could help with the code if you look for help.  I'm probably better suited for debugging issues more than the creative stuff.  ping me in need.

**Comment by xivk** [comment]
We're already using these:

https://github.com/osmbe/road-completion/blob/master/difference.js#L43

Focus is now first on getting this to work, next step is to work on more advanced case, I'm thinking topological-based checks. 

Last but not least performance when it's needed, currently it takes about 20mins to compare with wegenregister using 8 cores.
